# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sys-dashboard"
version = "0.1.0"
dependencies = [
    "typer[all]",
    "psutil",
    "rich",
]

[project.scripts]
sys-dashboard = "main:main"